### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by SY6502** [tux2bsd/freebsd-update-probe#1]
It seems the following file is missing on my installation and script cannot run:

/var/db/freebsd-update/pub.ssl

```
Can't open /var/db/freebsd-update/pub.ssl for reading, No such file or directory
34371047424:error:02001002:system library:fopen:No such file or directory:/usr/src/crypto/openssl/crypto/bio/bss_file.c:72:fopen('/var/db/freebsd-update/pub.ssl','r')
34371047424:error:2006D080:BIO routines:BIO_new_file:no such file:/usr/src/crypto/openssl/crypto/bio/bss_file.c:79:
unable to load Public Key
```

**Comment by reiphoNi9iey3qu** [comment]
> Can't open /var/db/freebsd-update/pub.ssl for reading, **No such file or directory**



Run `freebsd-update fetch install`, make sure your system is in a known good state and up to date.
See what FreeBSD versions freebsd-update-probe.sh works with (which you should have mentioned).
If you are playing with it in a FreeBSD Jail you are on your own.
(these things can deduced from https://github.com/tux2bsd/freebsd-update-probe#usage).

What was supplied points to a system/environment problem (of which there is no information).

Not a bug in freebsd-update-probe.sh, freebsd-update-probe.sh does not provide /var/db/freebsd-update/pub.ssl, it uses it. 

On FreeBSD 13.0 or 12.2.  Run `freebsd-update fetch install` so your system is in a known good state.  After that freebsd-update-probe.sh should run without issue, if it doesn't please respond with a better bug report (that includes some information about your environment and how you are running the script).

**Comment by reiphoNi9iey3qu** [comment]
I added a test to so that it will check the version of FreeBSD is a RELEASE version.

**Comment by reiphoNi9iey3qu** [comment]
and a test that it is being run by root

**Comment by reiphoNi9iey3qu** [comment]
By chance (fiddling with something else) I managed to reproduce this on FreeBSD 13.0, brand new install where `/usr/sbin/freebsd-update fetch [install]` had never been run.  I'll add a check (some time in the next few days).

**Comment by reiphoNi9iey3qu** [comment]
That check has been added.
